name: Model Comparison

on:
  push:
    branches:
      - feature/quiz2

jobs:
  compare_models:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Train and evaluate models
        run: python compare_models.py

      - name: Display results
        run: echo "::set-output name=production_accuracy::{accuracy_production}"
